require(dplyr)
require(maptools)
require(Hmisc)
require(reshape2)
require(shiny)
require(leaflet)
require(RJSONIO)
require(tidyr)
#require(data.table) #use only for preparation script
require(lubridate)
require(ggplot2)
require(reshape2)
library(plotly)
library(coda)
library(bsam)
library(MASS)


Sys.setenv(TZ='GMT')
mod <- readRDS(file="mod_hDCRWS_revi_150K_50K_50t_1h.rds")
mod$stepid<-1:nrow(mod)
densmod <- readRDS(file="revi_150K_50K_2chain_spatialdensity.rds")
birdraw <- readRDS(file="revi.rds")
birdraw <- birdraw %>% filter(id %in% unique(mod$id))
antennae <- readRDS(file="towers.rds")
towers <- antennae %>% group_by(site) %>% summarise_each(funs(first))
towers <- towers[-1,]
melt.towers <- melt(towers, measure=c("lat", "lon"))

track <- as.character(unique(mod$id))
